# Numpy Crash Course

In [2]:
import numpy as np

# This is a markdown

## Creating Arrays

In [11]:
my_list = [0,1,2,3,4]
print(my_list)

[0, 1, 2, 3, 4]


In [12]:
arr = np.array(my_list)

In [15]:
arr

array([0, 1, 2, 3, 4])

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
arr2=np.ones((2,4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
arr2.shape

(2, 4)

## Operations

In [34]:
np.random.seed(101) # SEED OF THE PSEUDORANDOM NUMBER GENERATOR
arr = np.random.randint(0,100,10)
print(arr)

[95 11 81 70 63 87 75  9 77 40]


In [35]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [43]:

arr2 = np.random.randint(0,100,10)

In [49]:
arr2

array([52, 13, 47, 49, 24, 20, 64, 52, 60, 47], dtype=int32)

In [ ]:
arr2.max()


In [ ]:
print(arr2.max())

64


In [51]:
arr.min()

np.int32(9)

In [52]:
arr.mean()

np.float64(60.8)

In [54]:

print(arr.argmin())

7


In [55]:
arr.argmax()

np.int64(0)

In [56]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40], dtype=int32)

In [59]:
arr3=arr.reshape(2,5)
arr3

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]], dtype=int32)

In [61]:
arr4=arr3.reshape(5,2)
arr4

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]], dtype=int32)

## Indexing

In [63]:
mat = np.arange(0,100).reshape(10,10)
print(mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [64]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
row = 0
col = 9

In [66]:
mat[row,col]

np.int64(9)

In [76]:
# With Slices
mat[:,col]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [67]:
mat[3:5,1:4]

array([[31, 32, 33],
       [41, 42, 43]])

In [68]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

# The end!